const reseñas = [
    { Titulo: "Yakuza: Fiancé", Estrellas: 5, Sinopsis: "Yoshino es la nieta del jefe de la mafia más poderosa de Osaka y siempre ha sido tratada de manera privilegiada. Pero un pacto entre su abuelo y otro gran mafioso de Tokyo pondrá su tranquila vida al revés. Kirishima, el nieto del mafioso tokiota con quien se supone que Yoshino acabará prometida, poco o nada tiene que ver con la imagen que muestra y no conseguirá engañar a la joven Yoshino, una mujer de armas tomar que no estará dispuesta a sucumbir ante este masoquista.", Resena: "Yakuza Fiancé es una serie refrescante y adictiva que logra combinar romance, acción y un toque de humor oscuro en un contexto poco común: el mundo de la yakuza. La dinámica entre Yoshino y Kirishima es fascinante, llena de tensión y con una evolución que atrapa desde el primer episodio. Los personajes son complejos y carismáticos, y su desarrollo es uno de los puntos fuertes de la serie. Además, la animación y el diseño de personajes están muy bien logrados, lo que potencia el tono único de la historia. Es un anime imperdible para quienes buscan un romance fuera de lo común y una trama que mezcla intriga y emociones intensas.", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 4.7, Sinopsis: "Esta entretenida historia de extraterrestres y fantasmas te dejará con ganas de más desde su primer capítulo. Oculto, un friki que cree en los ovnis, y Ayase, su compañera criada por una abuela médium, vivirán una historia que les hará cuestionarse todo lo que han creído hasta el momento… Comedia y romance se unen en este singular manga del que todo el mundo habla en Japón ¿te lo vas a perder?", Resena: "Dandadan es un anime que destaca por su mezcla única de acción sobrenatural, comedia y un toque de romance, manteniendo al espectador al borde de su asiento con su narrativa impredecible. La historia sigue a Momo y Okarun, dos adolescentes con personalidades y creencias opuestas que se unen para enfrentar sucesos paranormales, desde extraterrestres hasta fantasmas, en aventuras llenas de adrenalina y humor absurdo. La química entre los protagonistas es divertida y entrañable, creando un balance perfecto entre los momentos de tensión y comedia. Con una animación vibrante y creativa, Dandadan logra una experiencia visualmente sorprendente y altamente entretenida, ideal para quienes buscan una historia original y llena de giros inesperados.", Logo: "imagen aca" },
    { Titulo: "Bleach: Thousand-Year Blood War - The Conflict", Estrellas: 4.6, Sinopsis: "Bleach: Thousand-Year Blood War - The Conflict es la tercera parte de la adaptación al anime del arco final del manga homónimo de Tite Kubo. En esta parte, la historia continúa con la lucha de Ichigo y sus amigos contra Yhwach y los Quincy, y se espera que se revele más sobre el pasado de Yhwach.", Resena: "La tercera parte de *Bleach: Thousand-Year Blood War* es una explosión de emoción y nostalgia que lleva la épica batalla final de Ichigo y los shinigami contra los Quincy a un nivel superior. La animación de esta temporada es impresionante, con escenas de acción fluidas y detalladas que capturan la intensidad de cada enfrentamiento. Los personajes clásicos muestran un desarrollo profundo y emocional, mientras que nuevas habilidades y transformaciones sorprenden a los fans. La música y la dirección artística también contribuyen a la atmósfera épica de la serie. En conjunto, esta nueva entrega de *Bleach* es una experiencia imperdible para los seguidores de la franquicia, logrando un equilibrio entre la nostalgia y la innovación que mantiene la esencia de la historia original.", Logo: "imagen aca" },
    { Titulo: "I'll Become a Villainess Who Goes Down in History", Estrellas: 4.5, Sinopsis: 'La amable y compasiva heroína de un juego otome puede ser tan impecable como admirable, pero cierta joven de Japón prefiere mucho a la villana, Alicia Williams. Ella ve sentido en el despiadado abuso verbal de Alicia y valora su disciplina y fortaleza. Por otro lado, además de jugar siempre con las emociones del Príncipe Duke Seeker, la heroína plebeya parece solo hablar de labios para afuera. Si tuviera la opción, a la joven le encantaría reencarnarse como Alicia, ¡y su deseo de repente se hace realidad! Alicia, de siete años, despierta con los recuerdos de su vida pasada, ahora consciente de todos los eventos futuros, los resultados y los secretos del mundo. Ella no tiene miedo; Para burlar a la heroína y evitar un mal final, todo lo que Alicia necesita es trabajo duro, dominio de la magia oscura de su noble familia y la determinación de convertirse en la mayor villana de la historia.', Resena: "", Logo: "imagen aca" },
    { Titulo: "Blue Lock vs u20 Japan", Estrellas: 3.8, Sinopsis: "Los 11 jugadores seleccionados de Blue Lock se enfrentarán a la Selección Japonesa de Sub-20 en un partido representativo nacional que todo Japón podrá ver. El ganador se asegura el control del equipo nacional de Japón para el próximo Mundial de Sub-20, pero con Sae Itoshi liderando el equipo y Ryusei Shidou uniéndose a él, ¿cómo superará Blue Lock este inmenso desafío?", Resena: "El arco Blue Lock vs. U-20 Japan presenta una dinámica intensa entre los jugadores del programa Blue Lock y el equipo nacional U-20 de Japón. En este enfrentamiento, el anime explora temas de competencia y crecimiento personal, mientras los jugadores ponen a prueba sus habilidades y egos en el campo. La narrativa está cargada de tensión y emociones, aunque en ocasiones puede sentirse un poco predecible en cuanto a los giros y resoluciones. La animación logra capturar la energía de los partidos y las estrategias en juego, aunque no destaca en innovación visual. En general, este arco ofrece una experiencia sólida para los fanáticos del anime de deportes, con un enfoque en la evolución individual de cada personaje y su lucha por alcanzar la cima del fútbol.", Logo: "imagen aca" },
    { Titulo: "The Do-Over Damsel Conquers The Dragon Emperor", Estrellas: 3.8, Sinopsis: 'Jill Savelle, prometida del príncipe heredero Gerald de Kleitos y conocida como la "Dama Diosa de la Guerra", está siendo perseguida por el mismo país que juró proteger. Traicionada por su prometido, es acusada de traidora y encarcelada. En sus últimos momentos, Jill se arrepiente, pero justo cuando la muerte se acerca, despierta seis años en el pasado. Esta vez, ella no será un simple peón. Ahora, como una niña de 10 años, Jill decide escapar de su inminente compromiso con el príncipe. Para ello, en broma le profesa su amor al emperador dragón Hadis Teos Rave, de 19 años, quien un día manchará la tierra de sangre debido a la locura. Pero contra todas las expectativas, ¡acepta! A diferencia del tirano de los recuerdos de Jill, el Hadis de esta época es un emperador amable, aunque desafortunado. ¿Podrá Jill evitar que Hadis descienda por el mismo camino oscuro y malvado, o está atado a un futuro inevitable?", Resena: "*The Do-Over Damsel Conquers The Dragon Emperor* es un anime que combina romance, fantasía y aventura en una historia cautivadora sobre segundas oportunidades y superación personal. La protagonista, después de regresar en el tiempo tras una vida trágica, decide cambiar su destino y construir una relación distinta con el poderoso Emperador Dragón. Lo que realmente destaca es su determinación y el crecimiento emocional de ambos personajes, especialmente en su relación, que evoluciona de manera lenta pero significativa. La animación complementa bien la historia, con paisajes y escenas mágicas que crean una atmósfera envolvente. En general, este anime ofrece una experiencia entretenida y conmovedora para quienes disfrutan de historias de redención y romance en un mundo de fantasía.', Logo: "imagen aca" },
    { Titulo: "Uzumaki", Estrellas: 3.5, Sinopsis: "Hola", Resena: "El anime *Uzumaki*, basado en el manga de terror de Junji Ito, es una propuesta visualmente intrigante que busca capturar la atmósfera perturbadora de la obra original. La historia sigue a los habitantes de una ciudad que caen bajo una maldición espiral, mostrando sucesos cada vez más extraños y siniestros. La animación adopta un estilo monocromático que se apega fielmente al arte de Ito, recreando su estilo detallado y grotesco. Sin embargo, esta elección de estilo puede no ser del gusto de todos, ya que el ritmo lento y la estética oscura pueden sentirse densos. La serie destaca en su ambientación y tensión, ideal para los fanáticos del horror psicológico, aunque aquellos que prefieren tramas más dinámicas podrían encontrarla difícil de seguir.", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },
    { Titulo: "Dan Da Dan", Estrellas: 5, Sinopsis: "Hola", Resena: "Hola está bueno", Logo: "imagen aca" },

];

function GenerarListado(){
    console.log("Generando")
    const Lista = document.getElementById("AnimeTemporada");
    if (Lista){
        console.log("Existe")
    } else {
        console.error("NO")
    }
    reseñas.forEach((anime, index) => {
        // crear contenedor
        const animeDiv = document.createElement("div");
        animeDiv.classList.add("AnimeTemporada");

        // crear HTML
        animeDiv.innerHTML = `
        <h2>${index + 1}</h2>
        <h3>${anime.Titulo}</h3>
        <p class="descripcion">${anime.Sinopsis}</p>
        <p><strong>Estrellas:</strong> ${anime.Estrellas} / 5</p>
    `;
        Lista.appendChild(animeDiv)
        
    });
}
